### ISSUE TITLE
Not including the tipAmount in the objects where tip is included

### ISSUE THREAD

**Issue by haideryzai** [usama7365/developer-community#9]
`router.get("/transactionsForCustomer", auth, isCustomer, async (req, res) => {
  try {
    const transactionFilter = {
      customerId: req.user.id,
      action: {
        $in: [
          AMOUNT_PAID,
          REFUND,
          REFERRAL_BONUS,
          ADMIN_COMMISSION_ON_CANCEL,
          TIP,
          Fee,
          DRIVER_COMMISSION_ON_CANCEL,
        ],
      },
    };

    const limit = +req.query.limit ? +req.query.limit : 10;
    const page = Math.max(0, req.query.page);

    const transactions = await Transactions.find(transactionFilter)
      .sort({ createdAt: -1 })
      .populate("driverId", ["avatar", "firstName", "surName"])
      .populate([
        {
          path: "bookingId",
          model: "request",
          select: "breakdownType requestType",
          populate: {
            path: "selectedQuoteId",
            model: "quotes",
            select: "price",
          },
        },
      ])
      .populate({
        path: "quoteId",
        model: "quotes",
        select: "-driverId -vehicleId -requestId -createdAt -firebase_id",
        populate: {
          path: "coupon",
          model: "coupon", // Assuming coupon details are in a collection named 'Coupon'
        },
      })
      .limit(limit)
      .skip(limit * page);

  
    const tipTransactions = transactions.filter((item) => item.action == TIP);
    const feeTransactions = transactions.filter((item) => item.action == Fee);
    const driverCommTransactions = transactions.filter(
      (item) => item.action == DRIVER_COMMISSION_ON_CANCEL
    );

    tipTransactions.map((tip) => {
      let transactionArrayIndex = transactions.findIndex((currentValue) => {
        return (
          currentValue.bookingId == tip.bookingId &&
          tip._id != currentValue._id &&
          currentValue.action == AMOUNT_PAID
        );
      });
      // console.log("transactionArrayIndex", transactionArrayIndex);
      if (transactionArrayIndex > -1)
        transactions[transactionArrayIndex].amount += tip.amount;
        transactions[transactionArrayIndex].tipAmount = tip.amount
    });

    feeTransactions.map((fee) => {
      let transactionArrayIndex = transactions.findIndex((currentValue) => {
        return (
          currentValue.bookingId == fee.bookingId &&
          fee._id != currentValue._id &&
          currentValue.action == AMOUNT_PAID
        );
      });
      //console.log("transactionArrayIndex", transactionArrayIndex);
      if (transactionArrayIndex > -1)
        transactions[transactionArrayIndex].amount += fee.amount;
    });

    driverCommTransactions.map((dCommission) => {
      let transactionArrayIndex = transactions.findIndex((currentValue) => {
        return (
          currentValue.bookingId == dCommission.bookingId &&
          dCommission._id != currentValue._id &&
          currentValue.action == ADMIN_COMMISSION_ON_CANCEL
        );
      });
      //console.log("transactionArrayIndex", transactionArrayIndex);
      if (transactionArrayIndex > -1)
        transactions[transactionArrayIndex].amount += dCommission.amount;
    });

    const filteredOutTipAndDriverCommissionTransactions = transactions.filter(
      (item) => ![Fee, TIP, DRIVER_COMMISSION_ON_CANCEL].includes(item.action)
    );

    res.json({
      result: filteredOutTipAndDriverCommissionTransactions,
      status: true,
      msg: "customer transactions!",
    });
  } catch (error) {
    return res.json({ error: error.message });
  }
});`

**Comment by haideryzai** [comment]
I am trying to add tipAmount in transactions where tipAmount is added in a transaction, it works with existing properties like I can add it to the amount but whenever I try to assign the value of the tip to a new key like tipAmount, it doesn't work.

**Comment by usama7365** [comment]
The issue might be related to the fact that MongoDB documents are immutable by default, meaning that you cannot directly add or modify properties in the way you're attempting within the `map` function. However, since you are working with JavaScript objects in the code, you should be able to add new properties to these objects without issues.

Here’s a possible reason why the `tipAmount` is not being included in the objects:

1. **Reference Issue**: The `map` function in your code doesn't return the modified object, so the changes to `transactions[transactionArrayIndex]` might not persist outside the `map` function.
2. **Object Mutation**: Even though you are modifying the object directly, there might be something in the logic that overwrites or omits the `tipAmount` when constructing the final array.

### Solution:

You can explicitly add the `tipAmount` by ensuring that the modified transaction is retained correctly. Here's a revised version of your logic:

```javascript
const tipTransactions = transactions.filter((item) => item.action == TIP);

tipTransactions.forEach((tip) => {
  let transactionArrayIndex = transactions.findIndex((currentValue) => {
    return (
      currentValue.bookingId == tip.bookingId &&
      tip._id != currentValue._id &&
      currentValue.action == AMOUNT_PAID
    );
  });

  if (transactionArrayIndex > -1) {
    transactions[transactionArrayIndex].amount += tip.amount;
    // Adding the tipAmount property explicitly
    transactions[transactionArrayIndex] = {
      ...transactions[transactionArrayIndex],
      tipAmount: tip.amount,
    };
  }
});
```

### Explanation:
- **Spread Operator**: Using the spread operator `...transactions[transactionArrayIndex]`, we ensure that the original transaction object is not overwritten and the `tipAmount` is added to it.
- **`.forEach` instead of `.map`**: Since you are not using the returned array from `map`, I've switched it to `forEach`, which is more appropriate for mutation.

### After Making Changes:
After you apply the changes above, make sure to verify if the `tipAmount` is correctly added to the transactions in the final `filteredOutTipAndDriverCommissionTransactions` result.

This should fix the issue of `tipAmount` not being included in your transactions. 

If you continue to face issues, you might want to double-check the structure of your `transactions` array and ensure there’s no subsequent code that might be removing or overwriting the `tipAmount` property.

**Comment by haideryzai** [comment]
Thanks. As you said, mongodb documents are immutable, so I created deepcopy for the transactions array and then I was able to modify and add the tipAmount in them. And that solved my issue.
